version: '3.8'

services:
  compare-db:
    image: postgres:14
    environment:
      POSTGRES_DB: comparedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5440:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
